name: human_rights_museum_app
description: Human Rights Museum App prototype for sensor-based indoor/outdoor navigation.
publish_to: "none"
version: 0.1.8+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  flutter_blue_plus: ^1.35.5
  geolocator: ^14.0.2
  http: ^1.6.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.3
  sensors_plus: ^6.1.1
  supabase_flutter: ^2.10.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
